<a href="https://colab.research.google.com/github/LCaravaggio/DataExtraction/blob/main/Alphacast.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bajar base entera

In [2]:
from google.colab import userdata
API_key=userdata.get('ALPHACAST')

In [31]:
import requests
import pandas as pd
from io import StringIO

url_base='https://api.alphacast.io/datasets'
dataset='5359'
url = url_base + f'/{dataset}/data?apiKey={API_key}&$format=csv'

r1 = requests.get(url)

In [35]:
data = StringIO(r1.text)
df = pd.read_csv(data, delimiter=',')

In [36]:
df

,Date,country,AA22,AE38,AE38D,AL29,AL29D,AL30,AL30C,AL30D,...,TZXD7,TZX25,TZX28,X20Y4,TZXM6,S14O4,S29N4,S31E5,S28F5,S31M5
0,2005-01-06,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2005-01-07,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2005-01-10,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2005-01-11,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2005-01-12,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4887,2024-08-12,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,49.207,NaN,...,NaN,NaN,NaN,NaN,108.0,122.650,118.70,139.240,123.052,114.95
4888,2024-08-13,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,49.090,NaN,...,NaN,NaN,NaN,NaN,109.0,122.937,118.95,140.500,124.900,116.80
4889,2024-08-14,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,49.900,NaN,...,NaN,NaN,NaN,NaN,110.0,123.000,119.00,140.835,124.750,117.25
4890,2024-08-15,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,50.180,NaN,...,NaN,NaN,NaN,NaN,111.5,123.250,119.58,141.700,125.800,118.30
4891,2024-08-16,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,50.080,NaN,...,NaN,NaN,NaN,NaN,114.5,123.800,120.00,142.200,125.800,118.35

# Solo algunas variables

In [66]:
url_base='https://api.alphacast.io/datasets'
dataset='6042'
select = '79353'
url = url_base + f'/{dataset}/data?apiKey={API_key}&$select={select}&$format=csv'

r1 = requests.get(url)

In [67]:
data = StringIO(r1.text)
df = pd.read_csv(data, delimiter=',')

In [68]:
df

           Date    country  Sector privado no registrado
0    2015-10-01  Argentina                           NaN
1    2015-11-01  Argentina                           NaN
2    2015-12-01  Argentina                           NaN
3    2016-01-01  Argentina                           NaN
4    2016-02-01  Argentina                           NaN
..          ...        ...                           ...
100  2024-02-01  Argentina                       1829.42
101  2024-03-01  Argentina                       2007.72
102  2024-04-01  Argentina                       2163.76
103  2024-05-01  Argentina                       2419.24
104  2024-06-01  Argentina                       2642.13

[105 rows x 3 columns]

# Usando la librería

In [57]:
!pip install alphacast
from alphacast import Alphacast

Requirement already satisfied: alphacast in /usr/local/lib/python3.10/dist-packages (0.1.8.4)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from alphacast) (2.32.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from alphacast) (2.1.4)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.10/dist-packages (from alphacast) (1.0.1)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas->alphacast) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->alphacast) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->alphacast) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->alphacast) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->alphacast) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->alphacast) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->alphacast) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->alphacast) (2024.7.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->alphacast) (1.16.0)

In [60]:
alphacast = Alphacast(userdata.get('ALPHACAST'))
dataset = alphacast.datasets.dataset(5515)


df = dataset.download_data(format = "pandas", startDate=None, endDate=None, filterVariables = ["75061"], filterEntities = {})

In [61]:
df

          Date    country  Alimentos y bebidas no alcohólicas
0   2016-12-01  Argentina                            100.0000
1   2017-01-01  Argentina                            101.3024
2   2017-02-01  Argentina                            103.1605
3   2017-03-01  Argentina                            106.0143
4   2017-04-01  Argentina                            108.3515
..         ...        ...                                 ...
87  2024-03-01  Argentina                           6216.0451
88  2024-04-01  Argentina                           6590.0877
89  2024-05-01  Argentina                           6909.5535
90  2024-06-01  Argentina                           7117.2232
91  2024-07-01  Argentina                           7345.4071

[92 rows x 3 columns]